# -*- coding: utf-8 -*-
"""Assignment 3.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1djQeC1TCmHkSLkd9oLD1I3rW5kOWXfhz

Write a Python code to create a function called most_frequent that takes a string and prints the letters in decreasing order of frequency.
"""

def most_frequent(string):
  global dictionary
  dictionary= dict()
  for i in string:
    if i not in dictionary:
      dictionary[i]=1
    else:
      dictionary[i]=dictionary[i]+1
  return dictionary

def sorted_dict(a):
  sorted_d={key:value for key,value in sorted(dictionary.items(),reverse=True, key=lambda item:item[1])}
  return sorted_d





string="Mississippi"
count_of_letters= most_frequent(string)
sorted_count=sorted_dict(count_of_letters)
print(sorted_count)