# -*- coding: utf-8 -*-
"""Lets's Code OOPs.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qpls-meMxvDY9HnEF_gxGP_lkMY8NnhJ

Write a program in python for fibonacci numbers.
"""

sum=0
f1=0
f2=1
num= int(input("Enter the number till which you want to find the fibonacci series:"))
if(num==0):
  print(" The fibonacci series is 0")
if (num==1):
  print(" The fibonacci series is 1")
if (num<0):
  print("Fibonacci series can't be found for the negative number")
else:
  for i in range(2,num):
     sum=f1+f2
     f1=f2
     f2=sum
  print("The fibonacci series is:", f2)

"""Write a python program to print all the positive numbers in a range."""

lst= eval(input("Enter the elements of the list:"))
for i in lst:
  if i>0:
    print(i)